### ISSUE TITLE
ERROR (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:AddMatMat():cu-matrix.cc:1317) cublasStatus_t 13 : "CUBLAS_STATUS_EXECUTION_FAILED" returned from 'cublas_gemm(GetCublasHandle(), (transB==kTrans? CUBLAS_OP_T:CUBLAS_OP_N), (transA==kTrans? CUBLAS_OP_T:CUBLAS_OP_N), m, n, k, alpha, B.data_, B.Stride(), A.data_, A.Stride(), beta, data_, Stride())'

### ISSUE THREAD

**Issue by PigpigF** [kaldi-asr/kaldi#3693]

**Comment by PigpigF** [comment]
When I run pretrain_dbn.sh, the code exits before full completion. this is my rbm.1.log .

rbm-train-cd1-frmshuff --learn-rate=0.01 --l2-penalty=0.0002 --num-iters=6 --verbose=1 --feature-transform=exp/tri4a_dnn_pretrain_tr05_multi_enhancedGMM/final.feature_transform exp/tri4a_dnn_pretrain_tr05_multi_enhancedGMM/1.rbm.init 'ark:copy-feats scp:exp/tri4a_dnn_pretrain_tr05_multi_enhancedGMM/train.scp ark:- |' exp/tri4a_dnn_pretrain_tr05_multi_enhancedGMM/1.rbm 
WARNING (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:SelectGpuId():cu-device.cc:228) Not in compute-exclusive mode.  Suggestion: use 'nvidia-smi -c 3' to set compute exclusive mode
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:SelectGpuIdAuto():cu-device.cc:373) Selecting from 2 GPUs
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:SelectGpuIdAuto():cu-device.cc:388) cudaSetDevice(0): GeForce RTX 2080 Ti	free:10413M, used:575M, total:10988M, free/total:0.947659
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:SelectGpuIdAuto():cu-device.cc:388) cudaSetDevice(1): GeForce RTX 2080 Ti	free:10784M, used:204M, total:10989M, free/total:0.981368
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:SelectGpuIdAuto():cu-device.cc:435) Trying to select device: 1 (automatically), mem_ratio: 0.981368
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:SelectGpuIdAuto():cu-device.cc:454) Success selecting device 1 free mem ratio: 0.981368
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:FinalizeActiveGpu():cu-device.cc:308) The active GPU is [1]: GeForce RTX 2080 Ti	free:10686M, used:302M, total:10989M, free/total:0.972451 version 7.5
copy-feats scp:exp/tri4a_dnn_pretrain_tr05_multi_enhancedGMM/train.scp ark:- 
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:Init():nnet-randomizer.cc:32) Seeding by srand with : 777
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:main():rbm-train-cd1-frmshuff.cc:146) RBM TRAINING STARTED
LOG (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:main():rbm-train-cd1-frmshuff.cc:149) Iteration 1/6
ERROR (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:AddMatMat():cu-matrix.cc:1317) cublasStatus_t 13 : "CUBLAS_STATUS_EXECUTION_FAILED" returned from 'cublas_gemm(GetCublasHandle(), (transB==kTrans? CUBLAS_OP_T:CUBLAS_OP_N), (transA==kTrans? CUBLAS_OP_T:CUBLAS_OP_N), m, n, k, alpha, B.data_, B.Stride(), A.data_, A.Stride(), beta, data_, Stride())'

[ Stack-Trace: ]
rbm-train-cd1-frmshuff(kaldi::MessageLogger::LogMessage() const+0x82c) [0x5b8bbc]
rbm-train-cd1-frmshuff(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x21) [0x45e0bf]
rbm-train-cd1-frmshuff(kaldi::CuMatrixBase<float>::AddMatMat(float, kaldi::CuMatrixBase<float> const&, kaldi::MatrixTransposeType, kaldi::CuMatrixBase<float> const&, kaldi::MatrixTransposeType, float)+0x2e7) [0x4c5287]
rbm-train-cd1-frmshuff(kaldi::CuDevice::CheckGpuHealth()+0x1af) [0x4a64db]
rbm-train-cd1-frmshuff(main+0xbe2) [0x45c2c8]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f75bbc9c830]
rbm-train-cd1-frmshuff(_start+0x29) [0x45b619]

WARNING (rbm-train-cd1-frmshuff[5.5.522~1-3492d]:Close():kaldi-io.cc:515) Pipe copy-feats scp:exp/tri4a_dnn_pretrain_tr05_multi_enhancedGMM/train.scp ark:- | had nonzero return status 13
kaldi::KaldiFatalError

**Comment by danpovey** [comment]
Could be a permission issue in your NVidia compute cache, see if
`export CUDA_CACHE_DISABLE=1` fixes it.   Obviously do that in a way that the program can see.. e.g. in the path.sh.
If not probably some hard to debug driver issue.

**Comment by PigpigF** [comment]
> Could be a permission issue in your NVidia compute cache, see if
> `export CUDA_CACHE_DISABLE=1` fixes it. Obviously do that in a way that the program can see.. e.g. in the path.sh.
> If not probably some hard to debug driver issue.
Thank you very much，I try it but the error is same

**Comment by danpovey** [comment]
You could see if the test programs in cudamatrix/ run.
Please don't ask me how to run them; figure it out.

**Comment by mycrazycracy** [comment]
I have the same problem. The GPU is RTX 2080 Ti, cuda 9.1, cuda driver 435.21

**Comment by jtrmal** [comment]
I think for  RTX 2080 Ti you'd need cuda 10(.1)?
y.

**Comment by mycrazycracy** [comment]
@jtrmal Thanks! I've tried cuda 10.0 and that fixes the problem. I think cuda 10.1 should work as well

**Comment by signalogy** [comment]
Is this issue resolved? 

I am getting the same errors even with test code as follows. I am using CUDA 10.1 (v10.1.243) on Ubuntu 18.04

```
$ ./cu-tp-matrix-test
LOG ([5.5.635~1486-0e031]:SelectGpuId():cu-device.cc:153) Manually selected to compute on CPU.
LOG ([5.5.635~1486-0e031]:main():cu-tp-matrix-test.cc:212) Tests without GPU use succeeded.
LOG ([5.5.635~1486-0e031]:SelectGpuId():cu-device.cc:223) CUDA setup operating under Compute Exclusive Mode.
LOG ([5.5.635~1486-0e031]:FinalizeActiveGpu():cu-device.cc:308) The active GPU is [0]: GeForce RTX 2080 Ti	free:10712M, used:306M, total:11019M, free/total:0.972151 version 7.5
ERROR ([5.5.635~1486-0e031]:Invert():cu-tp-matrix.cc:78) cublasStatus_t 13 : "CUBLAS_STATUS_EXECUTION_FAILED" returned from 'cublas_trsm(GetCublasHandle(), dim, dim, alpha, tmp2.Data(), tmp2.Dim().stride, tmp.Data(), tmp.Dim().stride)'

[ Stack-Trace: ]
/xdata/kaldi/src/lib/libkaldi-base.so(kaldi::MessageLogger::LogMessage() const+0xb61) [0x7f5a4aa4b6f3]
./cu-tp-matrix-test(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x21) [0x55e4779c13c9]
/xdata/kaldi/src/lib/libkaldi-cudamatrix.so(kaldi::CuTpMatrix<float>::Invert()+0x42c) [0x7f5a4af89b28]
./cu-tp-matrix-test(void kaldi::CudaTpMatrixUnitTest<float>()+0x85) [0x55e4779c271f]
./cu-tp-matrix-test(main+0x143) [0x55e4779c1003]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f5a49e66b97]
./cu-tp-matrix-test(_start+0x2a) [0x55e4779c0dba]

terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)
```

**Comment by danpovey** [comment]
In your case it is likely some issue specific to your CUDA toolkit version,
hardware or machine.
More info on which tests in cudamatrix/ (if any) succeed and which fail
might help.  Also the output of `nvidia-smi`.
And let us know whether other things have previously successfully run on
your GPU.

**Comment by signalogy** [comment]
Thanks Dan,

The followings are successful in test (only in cudamatrix/),
```
cu-array-test
cu-compressed-matrix-test
cu-device-test
cu-math-test
cu-packed-matrix-test
cu-rand-speed-test
cu-sparse-matrix-test
cu-sp-matrix-speed-test
cu-sp-matrix-test
cu-vector-speed-test
cu-vector-test
```

And these are the failed ones.
```
cu-block-matrix-test
cu-matrix-speed-test
cu-matrix-test
cu-test
cu-tp-matrix-test
```
Tensorflow applications on this machine work fine. 
The output of `nvidia-smi`.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:01:00.0  On |                  N/A |
| 16%   40C    P8    26W / 250W |      1MiB / 11011MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:21:00.0 Off |                  N/A |
| 16%   35C    P8    17W / 250W |      1MiB / 11019MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  On   | 00000000:4B:00.0 Off |                  N/A |
| 24%   38C    P8    20W / 250W |      1MiB / 11019MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  On   | 00000000:4C:00.0 Off |                  N/A |
| 16%   32C    P8     1W / 250W |      1MiB / 11019MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

and the `nvcc --version`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by danpovey** [comment]
Check that you didn't make any modifications to Kaldi that might have
affected this,

Also make sure you've done `make depend` in src, then re-make, in case it's
a failure to compile something.
You should do `make clean` if you have updated the CUDA toolkit since you
configured Kaldi.

My guess is it's some problem specific to the CUDA toolkit version or
hardware that will be difficult to debug.

**Comment by signalogy** [comment]
Thank you Dan,
I will try to use different versions of CUDA toolkit (possibly easier than the current one).

**Comment by signalogy** [comment]
Just for an update. After the infinite loop of uninstalling and reinstalling, I've finally settled with CUDA 10.2. CUDA 10.0 also worked, but I've decided to use 10.2 as I need to build Tensorflow 2.x from the source anyways. Thanks for your help.

**Comment by danpovey** [comment]
OK cool.

**Comment by wwbnjsace** [comment]
my mistake is similar,when i cd src/cudamatrix, run cu-test,error happen, that is 

ERROR   (nnet3-chain-train2[5.5]:AddMatMat():cu-matrix.cc:1329) cublasStatus_t 13 :   "CUBLAS_STATUS_EXECUTION_FAILED" returned from   'cublas_gemm(GetCublasHandle(), (transB==kTrans? CUBLAS_OP_T:CUBLAS_OP_N),   (transA==kTrans? CUBLAS_OP_T:CUBLAS_OP_N), m, n, k, alpha, B.data_,   B.Stride(), A.data_, A.Stride(), beta, data_, Stride())'
--

my nvidia-smi is

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 51%   85C    P2   196W / 250W |   9921MiB / 11019MiB |     96%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:68:00.0 Off |                  N/A |
| 32%   48C    P8    21W / 250W |    315MiB / 11016MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

and the nvcc -V is

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

in /usr/local/cuda10.0 ,cuda-10.1 ,cuda-10.2 ,cuda-11.0, all the method do not solve the problems.

**Comment by danpovey** [comment]
show the error from the test program, that error was not from test.
