### ISSUE TITLE
Using GPU for diagnostics during RNNLM training fails

### ISSUE THREAD

**Issue by jrieber-iais** [kaldi-asr/kaldi#4068]
When running the train_rnnlm.sh script with the parameter "--use-gpu-for-diagnostics true" it will fail with a GPU out-of-memory exception.

I also tried removing the parallelism in the train_rnnlm.sh script by removing the & commands, but the problem still persists. I tried a lot to work around this problem, but it is impossible.

This is how compute_prob.0.log looks like after running it:

`
# rnnlm-get-egs --bos-symbol=2975553 --eos-symbol=2975554 --brk-symbol=2975555 --vocab-size=2975556 /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/text/dev.txt ark:- | rnnlm-compute-prob --use-gpu=yes /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/0.raw "rnnlm-get-word-embedding /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/word_feats.txt /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/feat_embedding.0.mat -|" ark:- 
# Started at Wed May 13 13:46:07 CEST 2020
#
rnnlm-get-egs --bos-symbol=2975553 --eos-symbol=2975554 --brk-symbol=2975555 --vocab-size=2975556 /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/text/dev.txt ark:- 
LOG (rnnlm-get-egs[5.5.773~1-8d7f6]:Process():rnnlm-example.cc:703) Processed 106 lines of input.
rnnlm-compute-prob --use-gpu=yes /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/0.raw 'rnnlm-get-word-embedding /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/word_feats.txt /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/feat_embedding.0.mat -|' ark:- 
LOG (rnnlm-compute-prob[5.5.773~1-8d7f6]:SelectGpuId():cu-device.cc:223) CUDA setup operating under Compute Exclusive Mode.
LOG (rnnlm-compute-prob[5.5.773~1-8d7f6]:FinalizeActiveGpu():cu-device.cc:308) The active GPU is [0]: GeForce GTX TITAN X	free:12008M, used:204M, total:12212M, free/total:0.983235 version 5.2
rnnlm-get-word-embedding /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/word_feats.txt /nm-raid/temp_no_bck/jrieber/IFINDER-1994/rnnlm_training_experimental/out/rnnlm/feat_embedding.0.mat - 
LOG (rnnlm-compute-prob[5.5.773~1-8d7f6]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 3999268864 bytes; current memory info is: free:6003M, used:6209M, total:12212M, free/total:0.491538
LOG (rnnlm-compute-prob[5.5.773~1-8d7f6]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 3999268864 bytes; current memory info is: free:2189M, used:10023M, total:12212M, free/total:0.179243
LOG (rnnlm-compute-prob[5.5.773~1-8d7f6]:PrintMemoryUsage():cu-allocator.cc:368) Memory usage: 7058256896/10295967744 bytes currently allocated/total-held; 288/2 blocks currently allocated/free; largest free/allocated block sizes are 3999268864/3237709312; time taken total/cudaMalloc is 0.0137205/0.0266583, synchronized the GPU 0 times out of 23 frees; device memory info: free:2189M, used:10023M, total:12212M, free/total:0.179243maximum allocated: 7058259968current allocated: 7058256896
ERROR (rnnlm-compute-prob[5.5.773~1-8d7f6]:AllocateNewRegion():cu-allocator.cc:527) Failed to allocate a memory region of 3999268864 bytes.  Possibly smaller minibatch size would help.  Memory info: free:2189M, used:10023M, total:12212M, free/total:0.179243 CUDA error: 'out of memory'

[ Stack-Trace: ]
rnnlm-compute-prob(kaldi::MessageLogger::LogMessage() const+0xd3b) [0x55f7d94f986b]
rnnlm-compute-prob(+0x2a6170) [0x55f7d9422170]
rnnlm-compute-prob(kaldi::CuMemoryAllocator::AllocateNewRegion(unsigned long)+0x701) [0x55f7d94246d1]
rnnlm-compute-prob(kaldi::CuMemoryAllocator::MallocPitch(unsigned long, unsigned long, unsigned long*)+0x15e) [0x55f7d942490e]
rnnlm-compute-prob(kaldi::CuMatrix<float>::Resize(int, int, kaldi::MatrixResizeType, kaldi::MatrixStrideType)+0x3fb) [0x55f7d93f5c9b]
rnnlm-compute-prob(+0x129c25) [0x55f7d92a5c25]
rnnlm-compute-prob(kaldi::rnnlm::ProcessRnnlmOutput(kaldi::rnnlm::RnnlmObjectiveOptions const&, kaldi::rnnlm::RnnlmExample const&, kaldi::rnnlm::RnnlmExampleDerived const&, kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float>*, kaldi::CuMatrixBase<float>*, float*, float*, float*, float*)+0xc6) [0x55f7d92a6216]
rnnlm-compute-prob(kaldi::rnnlm::RnnlmCoreComputer::ProcessOutput(kaldi::rnnlm::RnnlmExample const&, kaldi::rnnlm::RnnlmExampleDerived const&, kaldi::CuMatrixBase<float> const&, kaldi::nnet3::NnetComputer*, kaldi::CuMatrixBase<float>*, float*)+0x141) [0x55f7d92abdc1]
rnnlm-compute-prob(kaldi::rnnlm::RnnlmCoreComputer::Compute(kaldi::rnnlm::RnnlmExample const&, kaldi::rnnlm::RnnlmExampleDerived const&, kaldi::CuMatrixBase<float> const&, float*, kaldi::CuMatrixBase<float>*)+0x142) [0x55f7d92abfe2]
rnnlm-compute-prob(main+0x63c) [0x55f7d928d9bc]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7efd47906b97]
rnnlm-compute-prob(_start+0x2a) [0x55f7d929379a]

LOG (rnnlm-compute-prob[5.5.773~1-8d7f6]:PrintStatsOverall():rnnlm-core-training.cc:118) Overall objf is (-nan + -nan) = -nan over 0 words (weighted) in 0 minibatches; exact = (-nan + -nan) = -nan
LOG (rnnlm-compute-prob[5.5.773~1-8d7f6]:~CachingOptimizingCompiler():nnet-optimize.cc:710) 0.104 seconds taken in nnet3 compilation total (breakdown: 0.052 compilation, 0.0332 optimization, 0.00244 shortcut expansion, 0.0111 checking, 0 computing indexes, 0.0048 misc.) + 0 I/O.
kaldi::KaldiFatalError
ERROR (rnnlm-get-egs[5.5.773~1-8d7f6]:WriteIntegerVector():base/io-funcs-inl.h:227) Write failure in WriteIntegerVector.

[ Stack-Trace: ]
rnnlm-get-egs(kaldi::MessageLogger::LogMessage() const+0xd3b) [0x55b682d50f5b]
rnnlm-get-egs(+0xd12f0) [0x55b682c1a2f0]
rnnlm-get-egs(void kaldi::WriteIntegerVector<int>(std::ostream&, bool, std::vector<int, std::allocator<int> > const&)+0x177) [0x55b682c20177]
rnnlm-get-egs(kaldi::rnnlm::RnnlmExample::Write(std::ostream&, bool) const+0xfd) [0x55b682c1b9dd]
rnnlm-get-egs(kaldi::TableWriterArchiveImpl<kaldi::KaldiObjectHolder<kaldi::rnnlm::RnnlmExample> >::Write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::rnnlm::RnnlmExample const&)+0x1ee) [0x55b682c119ce]
rnnlm-get-egs(kaldi::rnnlm::RnnlmExampleCreator::ProcessOneMinibatch()+0x8f0) [0x55b682c1ea10]
rnnlm-get-egs(kaldi::rnnlm::RnnlmExampleCreator::~RnnlmExampleCreator()+0x38) [0x55b682c1f858]
rnnlm-get-egs(main+0x289) [0x55b682c09de9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fc504830b97]
rnnlm-get-egs(_start+0x2a) [0x55b682c0f81a]

WARNING (rnnlm-get-egs[5.5.773~1-8d7f6]:Write():util/kaldi-holder-inl.h:57) Exception caught writing Table object. kaldi::KaldiFatalError
WARNING (rnnlm-get-egs[5.5.773~1-8d7f6]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (rnnlm-get-egs[5.5.773~1-8d7f6]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write

[ Stack-Trace: ]
rnnlm-get-egs(kaldi::MessageLogger::LogMessage() const+0xd3b) [0x55b682d50f5b]
rnnlm-get-egs(+0xd12f0) [0x55b682c1a2f0]
rnnlm-get-egs(kaldi::rnnlm::RnnlmExampleCreator::ProcessOneMinibatch()+0xccc) [0x55b682c1edec]
rnnlm-get-egs(kaldi::rnnlm::RnnlmExampleCreator::~RnnlmExampleCreator()+0x38) [0x55b682c1f858]
rnnlm-get-egs(main+0x289) [0x55b682c09de9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fc504830b97]
rnnlm-get-egs(_start+0x2a) [0x55b682c0f81a]

terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
# Accounting: time=45 threads=1
# Ended (code 255) at Wed May 13 13:46:52 CEST 2020, elapsed time 45 seconds
`

**Comment by danpovey** [comment]
Likely you are using run.pl for parallelization, which does not keep track of the GPU  resources.
My suggestion: set the GPUs to exclusive mode (nvidia-smi -c 3), and in train_rnnlm.sh, change all instances of --use-gpu=yes to --use-gpu=wait.

**Comment by jrieber-iais** [comment]
Thanks for the quick comment, but it did not help. My GPUs are all running in exclusive mode and switching from "yes" to "wait" for --use-gpu did not help (both is described in the new log file, so my changes were effective). I am still getting the same issue.

**Comment by danpovey** [comment]
Try setting  --num-chunks-per-minibatch=32 to rnnlm-get-egs.  The default is 128.

**Comment by jrieber-iais** [comment]
Unfortunately, that did not help. It seems as if it initially loads some mini-batches onto the GPU memory. I can see 2 successive memory allocations instead of just one. The first one is successful, the second one fails.

**Comment by danpovey** [comment]
There may be something wrong with your model topology.

**Comment by jrieber-iais** [comment]
But the model training itself works well and we already successfully used the model to perform the rescoring. It all works fine, it is just the diagnostics step that we cannot successfully get to run on GPU. On CPU it works, but it is extremely slow.

**Comment by danpovey** [comment]
Probably the word embedding matrix is too large to entirely fit in memory.

**Comment by danpovey** [comment]
BTW there is no --use-gpu=wait in your log file

**Comment by jrieber-iais** [comment]
Yes, correct. Because it is not up-to-date. Please find attached the latest log file.
[Uploading compute_prob.0.log…]()

**Comment by jrieber-iais** [comment]
I also tried a much larger GPU. And it all fits during the model training, it is just the evaluation that fails.

**Comment by danpovey** [comment]
Try an even smaller minibatch size.  Your vocab size is extremely large (2 million).  This is expected to cause problems.

**Comment by jrieber-iais** [comment]
Thank you! Reducing the mini-batch size did the trick.

**Comment by pengzhendong** [comment]
There is another way to solve this problem.
Train the model without diagnostics (comment out the diagnostics code), and then use GPU for diagnostics.

**Comment by jrieber-iais** [comment]
Thank you!

**Comment by nshmyrev** [comment]
I had this issue for ages too and what I'm doing is removing parallel execution of train and evaluate stages to just sequential one. It doesn't really affect the training speed in simple setups. Maybe it would be nice to patch default setup one day.
